eslint:
  enabled: true
  config_file: .eslintrc.json
   version: 8.1.0
  file_patterns:
    - "*.js"
    - "*.ts"
  enabled_plugins:
    - eslint-plugin-react
    - eslint-plugin-import
    - eslint-plugin-prettier
    - eslint-plugin:@typescript-eslint
